# Generated by Django 5.2.17 on 2026-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_key',
            field=models.CharField(choices=[('knight-1', 'knight-1'), ('knight-2', 'knight-2'), ('knight-3', 'knight-3'), ('knight-4', 'knight-4')], default='knight-1', max_length=30),
        ),
    ]
